# Generated by Django 5.1.1 on 2024-09-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_community_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hostel',
            field=models.CharField(choices=[('biobaku', 'Prof. Saburi Biobaku Hall'), ('eni_njoku', 'Prof. Eni Njoku Hall'), ('mariere', 'Baluba Kingdom'), ('jaja', 'King Jaja Hall')], help_text="User's hostel"),
        ),
    ]
