# Generated by Django 5.1.1 on 2024-10-05 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_hostel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='User business name', max_length=100)),
                ('business_description', models.CharField(help_text='User business description', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date business profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date business profile was edited')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BUSINESS_PROFILE',
                'verbose_name_plural': 'BUSINESS_PROFILES',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date buyer profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date buyer profile was edited')),
                ('user', models.ForeignKey(help_text='Profile for buyers', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BUYER_PROFILE',
                'verbose_name_plural': 'BUYER_PROFILE',
                'ordering': ('-created_at',),
            },
        ),
    ]
