# Generated by Django 5.1.1 on 2024-10-07 19:39

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_businessownerprofile_buyerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessownerprofile',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(crop=None, default='profile_pic/default.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[400, 400], upload_to='profile_picture'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(crop=None, default='profile_pic/default.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[400, 400], upload_to='profile_picture'),
        ),
    ]
