# Generated by Django 5.0.6 on 2024-10-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_is_buyer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Community',
        ),
    ]
