# Generated by Django 5.0.6 on 2024-10-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='room_name',
        ),
    ]
