# Generated by Django 5.1.1 on 2024-09-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'PRODUCT', 'verbose_name_plural': 'PRODUCTS'},
        ),
    ]
