# Generated by Django 5.1.1 on 2024-09-22 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_products_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Order name', max_length=100)),
                ('quantity', models.IntegerField(default=1, help_text='Quantity of order placed')),
                ('short_code', models.CharField(help_text='Confirmation code for order', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date order was created/placed')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date order was modified')),
                ('order_owner', models.ForeignKey(help_text='User who placed the order', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Product the user ordered', on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'verbose_name': 'ORDER',
                'verbose_name_plural': 'ORDERS',
                'ordering': ['created_at'],
            },
        ),
    ]
