# Generated by Django 5.0.6 on 2024-10-24 19:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Community name', max_length=50)),
                ('description', models.TextField(help_text='Community description', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date the community was create')),
                ('community_members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
                ('community_owner', models.ForeignKey(help_text='Owner of the community', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'COMMUNITY',
                'verbose_name_plural': 'COMMUNITIES',
            },
        ),
    ]
